name: 'Terraform Apply'
on:
  push:
    branches:
      - "main"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/terraform-github-actions
          role-session-name: github-actions-session
          aws-region: ap-northeast-1

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init
      
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
