name: 'Terraform Plan'
on:
  pull_request

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/terraform-github-actions
          role-session-name: github-actions-session
          aws-region: ap-northeast-1

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init
        working-directory: terraform
      
      - name: Terraform validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
        working-directory: terraform

      - run: >
          echo ${{ steps.plan.outputs.stdout }}
          echo ${{ steps.plan.outputs.stderr }}
          echo ${{ steps.plan.outputs.exitcode }}
